[pytest]
addopts = --capture=no
markers =
    fuzz: mark test to run only with --fuzz flag
    live: mark test to run only with --live flag
    parallel: mark test to run in parallel with pytest-xdist
